export const ingredients = [
  { name: 'Водка Absolut' },
  { name: 'Водка Absolut Citron' },
  { name: 'Водка Absolut Crystal' },
  { name: 'Водка Absolut Elyx' },
  { name: 'Водка Absolut Kurant' },
  { name: 'Водка Absolut Mandarin' },
  { name: 'Водка Absolut Pear' },
  { name: 'Водка Absolut Peppar' },
  { name: 'Водка Absolut Vanilia' },
  { name: 'Водка Absolwent' }, // польская, зерновая
  { name: 'Водка Adnams' }, // британская, из ячменя/пшеницы/овса
  { name: 'Водка Aivy' }, // часто с вкусами
  { name: 'Водка Akvinta' },
  { name: 'Водка Altamura' },
  { name: 'Водка Anastasia' }, // американская, из кукурузы
  { name: 'Водка Arbikie' }, // шотландская крафтовая
  { name: 'Водка Arsenal' },
  { name: 'Водка Assaranca' },
  { name: 'Водка Au Vodka' }, // британская, золотая фильтрация
  { name: 'Водка Aval Dor' }, // валлийская, из кукурузы
  { name: 'Водка Avokado' },
  { name: 'Водка Aber Falls' }, // валлийская
  { name: 'Водка A' }, // российская премиум, кукурузная
  { name: 'Водка Air' }, // редкая, но встречается в списках (Air Company, CO2-based)
  { name: 'Водка Akula' }, // российская/украинская, иногда в A-lists
  { name: 'Водка Alkon' }, // российская
  { name: 'Водка Altai' }, // сибирская
  { name: 'Водка Amundsen' }, // норвежская/экспедиционная серия
  { name: 'Водка Ararat' }, // армянская, но иногда классифицируют как водку (хотя больше бренди)
  { name: 'Водка Atlantic' }, // европейская
  { name: 'Водка Babicka' },
  { name: 'Водка Baczewski' },
  { name: 'Водка Badachro' },
  { name: 'Водка Balkan' },
  { name: 'Водка Ballast Point' },
  { name: 'Водка Baller' },
  { name: 'Водка Beluga' },
  { name: 'Водка Beluga Noble' },
  { name: 'Водка Beluga Gold Line' },
  { name: 'Водка Beluga Transatlantic Racing' },
  { name: 'Водка Belvedere' },
  { name: 'Водка Belvedere Intense' },
  { name: 'Водка Belvedere Organic' },
  { name: 'Водка Belvedere Unfiltered' },
  { name: 'Водка Bimber' },
  { name: 'Водка Black Cow' },
  { name: 'Водка Black Shuck' },
  { name: 'Водка Blavod' },
  { name: 'Водка Bleu Roc' },
  { name: 'Водка Bols' },
  { name: 'Водка Bong Spirit' },
  { name: 'Водка BORU' },
  { name: 'Водка Boris Yeltsin' },
  { name: 'Водка Ballykeefe' },
  { name: 'Водка Bivrost' },
  { name: 'Водка Belaya Rus' },
  { name: 'Водка Белая Русь' },
  { name: 'Водка Беленькая' },
  { name: 'Водка Белая берёза' },
  { name: 'Водка Бульбашъ' },
  { name: 'Водка Батьківська' },
  { name: 'Водка Благов' },
  { name: 'Водка Бабий яр' },
  { name: 'Водка Баня' },
  { name: 'Водка Брестская' },
  { name: 'Водка Бульба' },
  { name: 'Водка Брестъ-Литовскъ' },
  { name: 'Водка Батькова' },
  { name: 'Водка Брест-Литовск' },
  { name: 'Водка Белая сова' },
  { name: 'Водка Белый аист' },
  { name: 'Водка Благородная' },
  { name: 'Водка Боярская' },
  { name: 'Водка Van Gogh' },
  { name: 'Водка Vault' },
  { name: 'Водка Vestal' },
  { name: 'Водка Virtuous' },
  { name: 'Водка VRSD' },
  { name: 'Водка Vulcanica' },
  { name: 'Водка Vladivar' },
  { name: 'Водка V-One' },
  { name: 'Водка V 5' },
  { name: 'Водка V Gallery' },
  { name: 'Водка Valt' },
  { name: 'Водка Vaudon' },
  { name: 'Водка Velho Barreiro' }, // иногда классифицируют как водку/кашасу, но в списках есть
  { name: 'Водка Verde Momento' },
  { name: 'Водка Villa Lobos' },
  { name: 'Водка Vincent Béjot' },
  { name: 'Водка VIVIR' },
  { name: 'Водка Vodka O' },
  { name: 'Водка Выборова' },
  { name: 'Водка Вкусняшка' },
  { name: 'Водка Вечерняя' },
  { name: 'Водка Владимирская' },
  { name: 'Водка Воля' },
  { name: 'Водка Вальс' },
  { name: 'Водка Вековая' },
  { name: 'Водка Весна' },
  { name: 'Водка Вечный зов' },
  { name: 'Водка Виртуоз' },
  { name: 'Водка Gattertop' },
  { name: 'Водка General John Stark' },
  { name: 'Водка Golden Egg' },
  { name: 'Водка Green Moon' },
  { name: 'Водка Grey Goose' },
  { name: "Водка Grey Goose L'Orange'" },
  { name: 'Водка Grey Goose Le Citron' },
  { name: 'Водка Gorbatschow' },
  { name: 'Водка Gorbatschow Premium' },
  { name: 'Водка Gorbatschow Platinum' },
  { name: 'Водка Георгиевская' },
  { name: 'Водка Гербовая' },
  { name: 'Водка Гжелка' },
  { name: 'Водка Гимаевская' },
  { name: 'Водка Главспирттрест' }, // историческая/серия
  { name: 'Водка Глазовская классическая' },
  { name: 'Водка Горбачёв' },
  { name: 'Водка Danzka' },
  { name: 'Водка Debowa' },
  { name: 'Водка Degen' },
  { name: 'Водка Desi Daru' },
  { name: 'Водка Dingle' },
  { name: 'Водка Discarded' },
  { name: 'Водка Dockyard' },
  { name: 'Водка Dry Fly' },
  { name: 'Водка Davna' },
  { name: 'Водка Diddly Squat Farm' },
  { name: 'Водка Diva Showgirl' },
  { name: 'Водка Doghouse' },
  { name: 'Водка Довгань' },
  { name: 'Водка Деревенский самогон' },
  { name: 'Водка Добрый фермер' },
  { name: 'Водка Дрова' },
  { name: 'Водка Дымка' },
  { name: 'Водка Дягилев' },
  { name: 'Водка Душепарка' },
  { name: 'Водка Edwards' },
  { name: 'Водка Eight Lands' },
  { name: 'Водка Eiko' },
  { name: 'Водка Ellers Farm' },
  { name: 'Водка Eristoff' },
  { name: 'Водка Eristow' },
  { name: 'Водка Eve' },
  { name: 'Водка East London Liquor Co.' },
  { name: 'Водка Ed Hardy' },
  { name: 'Водка Effen' },
  { name: 'Водка Emperor' },
  { name: 'Водка Ельцин' }, // Jelzin Vodka, российско-немецкая марка
  { name: 'Водка Ермак' },
  { name: 'Водка Журавли' },
  { name: 'Водка Журавли Премиум' },
  { name: 'Водка Живая' },
  { name: 'Водка Живая Классическая' },
  { name: 'Водка Живая водица' },
  { name: 'Водка Жемчужина Карелии' },
  { name: 'Водка Жемчужина Севера' },
  { name: 'Водка Жемчужина Севера Люкс' },
  { name: 'Водка Житняя Сльоза' },
  { name: 'Водка Житня Сльоза Бриллиантовая' },
  { name: 'Водка Живой рецепт' },
  { name: 'Водка Зеленая марка' },
  { name: 'Водка Зеленая марка Кедровая' },
  { name: 'Водка Зеленая марка Особая' },
  { name: 'Водка Зубровка' },
  { name: 'Водка Зубровка Bison Grass' },
  { name: 'Водка Зубровка Золотая' },
  { name: 'Водка Зубровка Black' },
  { name: 'Водка Зубр' },
  { name: 'Водка Золотая Русь' },
  { name: 'Водка Золотой резерв' },
  { name: 'Водка Золотая симфония' },
  { name: 'Водка Золотой зубр' },
  { name: 'Водка Зимняя деревенька' },
  { name: 'Водка Зимняя дорога' },
  { name: 'Водка Золотая' },
  { name: 'Водка Золотая осень' },
  { name: 'Водка Заря' },
  { name: 'Водка Золотой колос' },
  { name: 'Водка Золотое кольцо' },
  { name: 'Водка Iceberg' },
  { name: 'Водка Imperial' },
  { name: 'Водка Imperia' },
  { name: 'Водка Imperia by Stolichnaya' },
  { name: 'Водка Infusion' }, // редкая, иногда в flavored-линейках
  { name: 'Водка Irbis' },
  { name: 'Водка Ironroot' },
  { name: 'Водка Ice Queen' },
  { name: 'Водка Иней' },
  { name: 'Водка Интер' },
  { name: 'Водка Искра' },
  { name: 'Водка Кристалл' },
  { name: 'Водка Кристалл Столичная' },
  { name: 'Водка Кристалл Особая' },
  { name: 'Водка Кристалл Премиум' },
  { name: 'Водка Калашников' },
  { name: 'Водка Калашников Premium' },
  { name: 'Водка Кукуруза' },
  { name: 'Водка Кукуруза Классическая' },
  { name: 'Водка Казёнка' },
  { name: 'Водка Казённая' },
  { name: 'Водка Крепкая' },
  { name: 'Водка Крепкая Особая' },
  { name: 'Водка Хортица' },
  { name: 'Водка Хортица Премиум' },
  { name: 'Водка Хортица Серебряная' },
  { name: 'Водка Хортица Абсолютная' },
  { name: 'Водка Ketel One' },
  { name: 'Водка Kauffman' },
  { name: 'Водка Kauffman Private Collection' },
  { name: 'Водка Koskenkorva' },
  { name: 'Водка Кедровая' },
  { name: 'Водка Кедровица' },
  { name: 'Водка Ключ' },
  { name: 'Водка Клюквенная' }, // иногда чистая водка с клюквенным оттенком, но классическая
  { name: 'Водка Кауффман' },
  { name: 'Водка Капитанская' },
  { name: 'Водка Княжеская' },
  { name: 'Водка Князь Владимир' },
  { name: 'Водка Коса' },
  { name: 'Водка Крепыш' },
  { name: 'Водка Крымская' },
  { name: 'Водка Кубанская' },
  { name: 'Водка Курганная' },
  { name: 'Водка Курская' },
  { name: 'Водка Кяхтинская' },
  { name: 'Водка Лапландия' },
  { name: 'Водка Лапландия черносмородиновая' },
  { name: 'Водка Ледофф' },
  { name: 'Водка Граф Ледофф' },
  { name: 'Водка Граф Ледофф Аляска' },
  { name: 'Водка Легенда Кремля' },
  { name: 'Водка Ладога' },
  { name: 'Водка Ливіз' }, // Liviz, украинская/российская серия
  { name: 'Водка Лаб' },
  { name: 'Водка LAB№40' },
  { name: 'Водка LAB№50' },
  { name: 'Водка Лекс' },
  { name: 'Водка Liverpool' },
  { name: 'Водка Le Philtre' },
  { name: 'Водка Long Table' },
  { name: "Водка L'Chaim'" },
  { name: 'Водка Luchino' },
  { name: 'Водка Little Mountain Gorilla' },
  { name: 'Водка Legend of Kremlin' }, // иногда пишут Легенда Кремля
  { name: 'Водка Luksusowa' },
  { name: 'Водка Мамонт' },
  { name: 'Водка Мамонт Премиум' },
  { name: 'Водка Мороша' },
  { name: 'Водка Мороша Классическая' },
  { name: 'Водка Мороша Особая' },
  { name: 'Водка Мороша Премиум' },
  { name: 'Водка Московская' },
  { name: 'Водка Московская Особая' },
  { name: 'Водка Московская Кристалл' },
  { name: 'Водка Moskovskaya' },
  { name: 'Водка Monopolowa' },
  { name: 'Водка Minsk Kristall' },
  { name: 'Водка Мѣнскъ' },
  { name: 'Водка Мягков' },
  { name: 'Водка Мягков Премиум' },
  { name: 'Водка Мерная' },
  { name: 'Водка Мерная на молоке' },
  { name: 'Водка Мерная Премиум' },
  { name: 'Водка Медведь' },
  { name: 'Водка Медведь Белый' },
  { name: 'Водка Медведь Особая' },
  { name: 'Водка Мятная' },
  { name: 'Водка Мята' },
  { name: 'Водка Морошка' }, // иногда как водка с морошкой, но встречается как бренд
  { name: 'Водка Марал' },
  { name: 'Водка Мараль' },
  { name: 'Водка Монастырская' },
  { name: 'Водка Монарх' },
  { name: 'Водка Монако' },
  { name: 'Водка Motorhead' },
  { name: 'Водка Mermaid' },
  { name: 'Водка Mikkeller' },
  { name: 'Водка Meili' },
  { name: 'Водка Manguin' },
  { name: 'Водка Manly Spirits' },
  { name: 'Водка Mikolasch' },
  { name: 'Водка Mothaiba' },
  { name: 'Водка Nemiroff' },
  { name: 'Водка Nemiroff De Luxe' },
  { name: 'Водка Nemiroff Original' },
  { name: 'Водка Nemiroff Ukrainian Honey Pepper' },
  { name: 'Водка Nemiroff LEX' },
  { name: 'Водка Nemiroff The Inked Collection Bold Orange' },
  { name: 'Водка Nemiroff The Inked Collection Wild Cranberry' },
  { name: 'Водка Nemiroff The Inked Collection Burning Pear' },
  { name: 'Водка Nemiroff Birch Special' },
  { name: 'Водка Neft' },
  { name: 'Водка Nue' },
  { name: 'Водка Nikka' },
  { name: 'Водка Naga Chilli' },
  { name: 'Водка Народная' },
  { name: 'Водка Новая' },
  { name: 'Водка Новая Заря' },
  { name: 'Водка Новая Голден' },
  { name: 'Водка Ностальгия' },
  { name: 'Водка Номерная' },
  { name: 'Водка Ночная Москва' },
  { name: 'Водка Oddka' },
  { name: 'Водка Oval' },
  { name: 'Водка Outer Space' },
  { name: 'Водка Onegin' },
  { name: 'Водка O' }, // Vodka O, американская/органическая
  { name: 'Водка Orloff' },
  { name: 'Водка Oso Negro' },
  { name: 'Водка Original' }, // иногда как "Оригинальная" в сериях
  { name: 'Водка Онегин' },
  { name: 'Водка Оригинальная' },
  { name: 'Водка Охотничья' },
  { name: 'Водка Пять озёр' },
  { name: 'Водка Пять озёр Премиум' },
  { name: 'Водка Пять озёр Классическая' },
  { name: 'Водка Пять озёр Особая' },
  { name: 'Водка Парламент' },
  { name: 'Водка Парламент Премиум' },
  { name: 'Водка Первак' },
  { name: 'Водка Первак Домашний' },
  { name: 'Водка Первак Пшеничная' },
  { name: 'Водка Пшеничная' },
  { name: 'Водка Пшеничная Классическая' },
  { name: 'Водка Платиновая' },
  { name: 'Водка Платинка' },
  { name: 'Водка Премиум' },
  { name: 'Водка Премиум Кристалл' },
  { name: 'Водка Праздничная' },
  { name: 'Водка Посольская' },
  { name: 'Водка Птичка Синичка' },
  { name: 'Водка Правдинская' },
  { name: 'Водка Pravda' },
  { name: 'Водка Potocki' },
  { name: 'Водка Polmos' },
  { name: 'Водка Portobello Road' },
  { name: 'Водка Purity' },
  { name: 'Водка Pau Maui' },
  { name: 'Водка Pienaar and Son' },
  { name: 'Водка Pod' },
  { name: 'Водка Попов' },
  { name: 'Водка Полярная' },
  { name: 'Водка Подмосковная' },
  { name: 'Водка Прима' },
  { name: 'Водка Привоз' },
  { name: 'Водка Прохоровское поле' },
  { name: 'Водка Русский стандарт' },
  { name: 'Водка Русский стандарт Оригинал' },
  { name: 'Водка Русский стандарт Платинум' },
  { name: 'Водка Русский стандарт Голд' },
  { name: 'Водка Русская' },
  { name: 'Водка Русская оригинальная' },
  { name: 'Водка Русская премиум' },
  { name: 'Водка Ржаная' },
  { name: 'Водка Ржаная классическая' },
  { name: 'Водка Родниковая' },
  { name: 'Водка Родник' },
  { name: 'Водка Родная' },
  { name: 'Водка Родная земля' },
  { name: 'Водка Романова' },
  { name: 'Водка Romanov' },
  { name: 'Водка Ruskova' },
  { name: 'Водка Reyka' },
  { name: 'Водка Ramsbury' },
  { name: 'Водка Retribution' },
  { name: 'Водка Respirited' },
  { name: 'Водка Roberto Cavalli' },
  { name: 'Водка Rutte' },
  { name: 'Водка Рублёвка' },
  { name: 'Водка Рубиновая' },
  { name: 'Водка Радомир' },
  { name: 'Водка Радость' },
  { name: 'Водка Разливная' },
  { name: 'Водка Региональная' },
  { name: 'Водка Рекорд' },
  { name: 'Водка Ретро' },
  { name: 'Водка Столичная' },
  { name: 'Водка Столичная Классическая' },
  { name: 'Водка Столичная Премиум' },
  { name: 'Водка Столичная Север' },
  { name: 'Водка Смирнофф' },
  { name: 'Водка Смирнофф Red Label' },
  { name: 'Водка Смирнофф No. 21' },
  { name: 'Водка Смирновъ' },
  { name: 'Водка Смирновъ №21' },
  { name: 'Водка Союз' },
  { name: 'Водка Серебряная' },
  { name: 'Водка Серебро Сибири' },
  { name: 'Водка Сибирская' },
  { name: 'Водка Сибирская кедровая' },
  { name: 'Водка Северное золото' },
  { name: 'Водка Славянская' },
  { name: 'Водка Славянская Премиум' },
  { name: 'Водка Старая марка' },
  { name: 'Водка Старая Казань' },
  { name: 'Водка Старая Москва' },
  { name: 'Водка Снежная' },
  { name: 'Водка Снежница' },
  { name: 'Водка Снежный барс' },
  { name: 'Водка Skyy' },
  { name: 'Водка Svedka' },
  { name: 'Водка Sacred' },
  { name: 'Водка Sipsmith' },
  { name: 'Водка Sauvelle' },
  { name: 'Водка Sheringham' },
  { name: 'Водка Silver Circle' },
  { name: 'Водка Spirit of Hven' },
  { name: 'Водка Savvy' },
  { name: 'Водка Snow' },
  { name: 'Водка Scorpion' },
  { name: 'Водка Silver Tree' },
  { name: 'Водка Сибирский характер' },
  { name: 'Водка Сосновый бор' },
  { name: 'Водка Солнечная' },
  { name: 'Водка София' },
  { name: 'Водка София Премиум' },
  { name: 'Водка София Золото' },
  { name: 'Водка Absolut' },
  { name: 'Водка Absolut Citron' },
  { name: 'Водка Absolut Kurant' },
  { name: 'Водка Absolut Elyx' },
  { name: 'Водка Beluga' },
  { name: 'Водка Beluga Noble' },
  { name: 'Водка Belvedere' },
  { name: 'Водка Belvedere Intense' },
  { name: 'Водка Grey Goose' },
  { name: "Водка Grey Goose L'Orange'" },
  { name: 'Водка Ketel One' },
  { name: 'Водка Smirnoff' },
  { name: 'Водка Smirnoff Red Label' },
  { name: 'Водка Smirnoff No. 21' },
  { name: 'Водка Stolichnaya' },
  { name: 'Водка Stoli' },
  { name: 'Водка Tito’s Handmade Vodka' },
  { name: 'Водка Finlandia' },
  { name: 'Водка Skyy' },
  { name: 'Водка Svedka' },
  { name: 'Водка Russian Standard' },
  { name: 'Водка Nemiroff' },
  { name: 'Водка Хортица' },
  { name: 'Водка Зеленая марка' },
  { name: 'Водка Беленькая' },
  { name: 'Водка Пять озер' },
  { name: 'Водка Белуга' },
  { name: 'Водка Царская' },
  { name: 'Водка Русский размер' },
  { name: 'Водка Журавли' },
  { name: 'Водка Парламент' },
  { name: 'Водка Союз' },
  { name: 'Водка Чистые росы' },
  { name: 'Водка Мамонт' },
  { name: 'Водка Onegin' },
  { name: 'Водка Zubrowka' },
  { name: 'Водка Zubrowka Bizon' },
  { name: 'Водка Crystal Head' },
  { name: 'Водка Chopin' },
  { name: 'Водка Ciroc' },
  { name: 'Водка Effen' },
  { name: 'Водка Hangar One' },
  { name: 'Водка Pinnacle' },
  { name: 'Водка New Amsterdam' },
  { name: 'Водка Wyborowa' },
  { name: 'Водка Absolut' },
  { name: 'Водка Absolut Citron' },
  { name: 'Водка Absolut Crystal' },
  { name: 'Водка Absolut Elyx' },
  { name: 'Водка Absolut Kurant' },
  { name: 'Водка Absolut Mandarin' },
  { name: 'Водка Absolut Pear' },
  { name: 'Водка Absolut Peppar' },
  { name: 'Водка Absolut Vanilia' },
  { name: 'Водка Absolwent' }, // польская, зерновая
  { name: 'Водка Adnams' }, // британская, из ячменя/пшеницы/овса
  { name: 'Водка Aivy' }, // часто с вкусами
  { name: 'Водка Akvinta' },
  { name: 'Водка Altamura' },
  { name: 'Водка Anastasia' }, // американская, из кукурузы
  { name: 'Водка Arbikie' }, // шотландская крафтовая
  { name: 'Водка Arsenal' },
  { name: 'Водка Assaranca' },
  { name: 'Водка Au Vodka' }, // британская, золотая фильтрация
  { name: 'Водка Aval Dor' }, // валлийская, из кукурузы
  { name: 'Водка Avokado' },
  { name: 'Водка Aber Falls' }, // валлийская
  { name: 'Водка A' }, // российская премиум, кукурузная
  { name: 'Водка Air' }, // редкая, но встречается в списках (Air Company, CO2-based)
  { name: 'Водка Akula' }, // российская/украинская, иногда в A-lists
  { name: 'Водка Alkon' }, // российская
  { name: 'Водка Altai' }, // сибирская
  { name: 'Водка Amundsen' }, // норвежская/экспедиционная серия
  { name: 'Водка Ararat' }, // армянская, но иногда классифицируют как водку (хотя больше бренди)
  { name: 'Водка Atlantic' }, // европейская
  { name: 'Водка Babicka' },
  { name: 'Водка Baczewski' },
  { name: 'Водка Badachro' },
  { name: 'Водка Balkan' },
  { name: 'Водка Ballast Point' },
  { name: 'Водка Baller' },
  { name: 'Водка Beluga' },
  { name: 'Водка Beluga Noble' },
  { name: 'Водка Beluga Gold Line' },
  { name: 'Водка Belvedere' },
  { name: 'Водка Belvedere Intense' },
  { name: 'Водка Belvedere Organic' },
  { name: 'Водка Bimber' },
  { name: 'Водка Black Cow' },
  { name: 'Водка Black Shuck' },
  { name: 'Водка Blavod' },
  { name: 'Водка Bleu Roc' },
  { name: 'Водка Bols' },
  { name: 'Водка Bong Spirit' },
  { name: 'Водка BORU' },
  { name: 'Водка Belaya Rus' },
  { name: 'Водка Белая Русь' },
  { name: 'Водка Беленькая' },
  { name: 'Водка Белая берёза' },
  { name: 'Водка Бульбашъ' },
  { name: 'Водка Батьківська' },
  { name: 'Водка Благов' },
  { name: 'Водка Бабий яр' },
  { name: 'Водка Баня' },
  { name: 'Водка Брестская' },
  { name: 'Водка Бульба' },
  { name: 'Водка Бальзам' }, // иногда классифицируют как водку/настойку, но встречается
  { name: 'Водка Bivrost' },
  { name: 'Водка Ballykeefe' },
  { name: 'Водка Boris Yeltsin' },
  { name: 'Водка Babicka' },
  { name: 'Водка Baczewski' },
  { name: 'Водка Badachro' },
  { name: 'Водка Balkan' },
  { name: 'Водка Ballast Point' },
  { name: 'Водка Baller' },
  { name: 'Водка Beluga' },
  { name: 'Водка Beluga Noble' },
  { name: 'Водка Beluga Gold Line' },
  { name: 'Водка Beluga Transatlantic Racing' },
  { name: 'Водка Belvedere' },
  { name: 'Водка Belvedere Intense' },
  { name: 'Водка Belvedere Organic' },
  { name: 'Водка Belvedere Unfiltered' },
  { name: 'Водка Bimber' },
  { name: 'Водка Black Cow' },
  { name: 'Водка Black Shuck' },
  { name: 'Водка Blavod' },
  { name: 'Водка Bleu Roc' },
  { name: 'Водка Bols' },
  { name: 'Водка Bong Spirit' },
  { name: 'Водка BORU' },
  { name: 'Водка Boris Yeltsin' },
  { name: 'Водка Ballykeefe' },
  { name: 'Водка Bivrost' },
  { name: 'Водка Belaya Rus' },
  { name: 'Водка Белая Русь' },
  { name: 'Водка Беленькая' },
  { name: 'Водка Белая берёза' },
  { name: 'Водка Бульбашъ' },
  { name: 'Водка Батьківська' },
  { name: 'Водка Благов' },
  { name: 'Водка Бабий яр' },
  { name: 'Водка Баня' },
  { name: 'Водка Брестская' },
  { name: 'Водка Бульба' },
  { name: 'Водка Брестъ-Литовскъ' },
  { name: 'Водка Батькова' },
  { name: 'Водка Брест-Литовск' },
  { name: 'Водка Белая сова' },
  { name: 'Водка Белый аист' },
  { name: 'Водка Благородная' },
  { name: 'Водка Боярская' },
  { name: 'Водка Van Gogh' },
  { name: 'Водка Vault' },
  { name: 'Водка Vestal' },
  { name: 'Водка Virtuous' },
  { name: 'Водка VRSD' },
  { name: 'Водка Vulcanica' },
  { name: 'Водка Vladivar' },
  { name: 'Водка V-One' },
  { name: 'Водка V 5' },
  { name: 'Водка V Gallery' },
  { name: 'Водка Valt' },
  { name: 'Водка Vaudon' },
  { name: 'Водка Velho Barreiro' }, // иногда классифицируют как водку/кашасу, но в списках есть
  { name: 'Водка Verde Momento' },
  { name: 'Водка Villa Lobos' },
  { name: 'Водка Vincent Béjot' },
  { name: 'Водка VIVIR' },
  { name: 'Водка Vodka O' },
  { name: 'Водка Выборова' },
  { name: 'Водка Вкусняшка' },
  { name: 'Водка Вечерняя' },
  { name: 'Водка Владимирская' },
  { name: 'Водка Воля' },
  { name: 'Водка Вальс' },
  { name: 'Водка Вековая' },
  { name: 'Водка Весна' },
  { name: 'Водка Вечный зов' },
  { name: 'Водка Виртуоз' },
  { name: 'Водка Gattertop' },
  { name: 'Водка General John Stark' },
  { name: 'Водка Golden Egg' },
  { name: 'Водка Green Moon' },
  { name: 'Водка Grey Goose' },
  { name: "Водка Grey Goose L'Orange'" },
  { name: 'Водка Grey Goose Le Citron' },
  { name: 'Водка Gorbatschow' },
  { name: 'Водка Gorbatschow Premium' },
  { name: 'Водка Gorbatschow Platinum' },
  { name: 'Водка Георгиевская' },
  { name: 'Водка Гербовая' },
  { name: 'Водка Гжелка' },
  { name: 'Водка Гимаевская' },
  { name: 'Водка Главспирттрест' }, // историческая/серия
  { name: 'Водка Глазовская классическая' },
  { name: 'Водка Горбачёв' },
  { name: 'Водка Danzka' },
  { name: 'Водка Debowa' },
  { name: 'Водка Degen' },
  { name: 'Водка Desi Daru' },
  { name: 'Водка Dingle' },
  { name: 'Водка Discarded' },
  { name: 'Водка Dockyard' },
  { name: 'Водка Dry Fly' },
  { name: 'Водка Davna' },
  { name: 'Водка Diddly Squat Farm' },
  { name: 'Водка Diva Showgirl' },
  { name: 'Водка Doghouse' },
  { name: 'Водка Довгань' },
  { name: 'Водка Деревенский самогон' },
  { name: 'Водка Добрый фермер' },
  { name: 'Водка Дрова' },
  { name: 'Водка Дымка' },
  { name: 'Водка Дягилев' },
  { name: 'Водка Душепарка' },
  { name: 'Водка Edwards' },
  { name: 'Водка Eight Lands' },
  { name: 'Водка Eiko' },
  { name: 'Водка Ellers Farm' },
  { name: 'Водка Eristoff' },
  { name: 'Водка Eristow' },
  { name: 'Водка Eve' },
  { name: 'Водка East London Liquor Co.' },
  { name: 'Водка Ed Hardy' },
  { name: 'Водка Effen' },
  { name: 'Водка Emperor' },
  { name: 'Водка Ельцин' }, // Jelzin Vodka, российско-немецкая марка
  { name: 'Водка Ермак' }, // от Московского ЛВЗ "Ермак"
  { name: 'Водка Журавли' },
  { name: 'Водка Журавли Премиум' },
  { name: 'Водка Живая' },
  { name: 'Водка Живая Классическая' },
  { name: 'Водка Живая водица' },
  { name: 'Водка Жемчужина Карелии' },
  { name: 'Водка Жемчужина Севера' },
  { name: 'Водка Жемчужина Севера Люкс' },
  { name: 'Водка Житняя Сльоза' },
  { name: 'Водка Житня Сльоза Бриллиантовая' },
  { name: 'Водка Живой рецепт' },
  { name: 'Водка Зеленая марка' },
  { name: 'Водка Зеленая марка Кедровая' },
  { name: 'Водка Зеленая марка Особая' },
  { name: 'Водка Зубровка' },
  { name: 'Водка Зубровка Bison Grass' },
  { name: 'Водка Зубровка Золотая' },
  { name: 'Водка Зубровка Black' },
  { name: 'Водка Зубр' },
  { name: 'Водка Золотая Русь' },
  { name: 'Водка Золотой резерв' },
  { name: 'Водка Золотая симфония' },
  { name: 'Водка Золотой зубр' },
  { name: 'Водка Зимняя деревенька' },
  { name: 'Водка Зимняя дорога' },
  { name: 'Водка Золотая' },
  { name: 'Водка Золотая осень' },
  { name: 'Водка Заря' },
  { name: 'Водка Золотой колос' },
  { name: 'Водка Золотое кольцо' },
  { name: 'Водка Iceberg' },
  { name: 'Водка Imperial' },
  { name: 'Водка Imperia' },
  { name: 'Водка Imperia by Stolichnaya' },
  { name: 'Водка Infusion' }, // редкая, иногда в flavored-линейках
  { name: 'Водка Irbis' },
  { name: 'Водка Ironroot' },
  { name: 'Водка Ice Queen' },
  { name: 'Водка Иней' },
  { name: 'Водка Интер' },
  { name: 'Водка Искра' },
  { name: 'Водка Кристалл' },
  { name: 'Водка Кристалл Столичная' },
  { name: 'Водка Кристалл Особая' },
  { name: 'Водка Кристалл Премиум' },
  { name: 'Водка Калашников' },
  { name: 'Водка Калашников Premium' },
  { name: 'Водка Кукуруза' },
  { name: 'Водка Кукуруза Классическая' },
  { name: 'Водка Казёнка' },
  { name: 'Водка Казённая' },
  { name: 'Водка Крепкая' },
  { name: 'Водка Крепкая Особая' },
  { name: 'Водка Хортица' },
  { name: 'Водка Хортица Премиум' },
  { name: 'Водка Хортица Серебряная' },
  { name: 'Водка Хортица Абсолютная' },
  { name: 'Водка Ketel One' },
  { name: 'Водка Kauffman' },
  { name: 'Водка Kauffman Private Collection' },
  { name: 'Водка Koskenkorva' },
  { name: 'Водка Khortytsia' }, // английская транслитерация, но часто используется
  { name: 'Водка Кедровая' },
  { name: 'Водка Кедровица' },
  { name: 'Водка Ключ' },
  { name: 'Водка Клюквенная' }, // иногда чистая водка с клюквенным оттенком, но классическая
  { name: 'Водка Кауффман' },
  { name: 'Водка Капитанская' },
  { name: 'Водка Княжеская' },
  { name: 'Водка Князь Владимир' },
  { name: 'Водка Коса' },
  { name: 'Водка Крепыш' },
  { name: 'Водка Крымская' },
  { name: 'Водка Кубанская' },
  { name: 'Водка Курганная' },
  { name: 'Водка Курская' },
  { name: 'Водка Кяхтинская' },
  { name: 'Водка Л' },
  { name: 'Водка Лапландия' },
  { name: 'Водка Лапландия черносмородиновая' },
  { name: 'Водка Ледофф' },
  { name: 'Водка Граф Ледофф' },
  { name: 'Водка Граф Ледофф Аляска' },
  { name: 'Водка Легенда Кремля' },
  { name: 'Водка Ладога' },
  { name: 'Водка Ливіз' }, // Liviz, украинская/российская серия
  { name: 'Водка Лаб' },
  { name: 'Водка LAB№40' },
  { name: 'Водка LAB№50' },
  { name: 'Водка Лекс' },
  { name: 'Водка Liverpool' },
  { name: 'Водка Le Philtre' },
  { name: 'Водка Long Table' },
  { name: "Водка L'Chaim'" },
  { name: 'Водка Luchino' },
  { name: 'Водка Little Mountain Gorilla' },
  { name: 'Водка Legend of Kremlin' }, // иногда пишут Легенда Кремля
  { name: 'Водка Luksusowa' },
  { name: 'Водка Мамонт' },
  { name: 'Водка Мамонт Премиум' },
  { name: 'Водка Мороша' },
  { name: 'Водка Мороша Классическая' },
  { name: 'Водка Мороша Особая' },
  { name: 'Водка Мороша Премиум' },
  { name: 'Водка Московская' },
  { name: 'Водка Московская Особая' },
  { name: 'Водка Московская Кристалл' },
  { name: 'Водка Moskovskaya' },
  { name: 'Водка Monopolowa' },
  { name: 'Водка Minsk Kristall' },
  { name: 'Водка Мѣнскъ' },
  { name: 'Водка Мягков' },
  { name: 'Водка Мягков Премиум' },
  { name: 'Водка Мерная' },
  { name: 'Водка Мерная на молоке' },
  { name: 'Водка Мерная Премиум' },
  { name: 'Водка Медведь' },
  { name: 'Водка Медведь Белый' },
  { name: 'Водка Медведь Особая' },
  { name: 'Водка Мятная' },
  { name: 'Водка Мята' },
  { name: 'Водка Морошка' }, // иногда как водка с морошкой, но встречается как бренд
  { name: 'Водка Марал' },
  { name: 'Водка Мараль' },
  { name: 'Водка Монастырская' },
  { name: 'Водка Монарх' },
  { name: 'Водка Монако' },
  { name: 'Водка Motorhead' },
  { name: 'Водка Mermaid' },
  { name: 'Водка Mikkeller' },
  { name: 'Водка Meili' },
  { name: 'Водка Manguin' },
  { name: 'Водка Manly Spirits' },
  { name: 'Водка Mikolasch' },
  { name: 'Водка Mothaiba' },
  { name: 'Водка Nemiroff' },
  { name: 'Водка Nemiroff De Luxe' },
  { name: 'Водка Nemiroff Original' },
  { name: 'Водка Nemiroff Ukrainian Honey Pepper' },
  { name: 'Водка Nemiroff LEX' },
  { name: 'Водка Nemiroff The Inked Collection Bold Orange' },
  { name: 'Водка Nemiroff The Inked Collection Wild Cranberry' },
  { name: 'Водка Nemiroff The Inked Collection Burning Pear' },
  { name: 'Водка Nemiroff Birch Special' },
  { name: 'Водка Neft' },
  { name: 'Водка Nue' },
  { name: 'Водка Nikka' },
  { name: 'Водка Naga Chilli' },
  { name: 'Водка Народная' },
  { name: 'Водка Новая' },
  { name: 'Водка Новая Заря' },
  { name: 'Водка Новая Голден' },
  { name: 'Водка Ностальгия' },
  { name: 'Водка Номерная' },
  { name: 'Водка Ночная Москва' },
  { name: 'Водка Oddka' },
  { name: 'Водка Oval' },
  { name: 'Водка Outer Space' },
  { name: 'Водка Onegin' },
  { name: 'Водка O' }, // Vodka O, американская/органическая
  { name: 'Водка Orloff' },
  { name: 'Водка Oso Negro' },
  { name: 'Водка Original' }, // иногда как "Оригинальная" в сериях
  { name: 'Водка Онегин' },
  { name: 'Водка Оригинальная' },
  { name: 'Водка Охотничья' }, // иногда классифицируют как водку/настойку, но встречается
  { name: 'Водка Пять озёр' },
  { name: 'Водка Пять озёр Премиум' },
  { name: 'Водка Пять озёр Классическая' },
  { name: 'Водка Пять озёр Особая' },
  { name: 'Водка Парламент' },
  { name: 'Водка Парламент Премиум' },
  { name: 'Водка Первак' },
  { name: 'Водка Первак Домашний' },
  { name: 'Водка Первак Пшеничная' },
  { name: 'Водка Пшеничная' },
  { name: 'Водка Пшеничная Классическая' },
  { name: 'Водка Платиновая' },
  { name: 'Водка Платинка' },
  { name: 'Водка Премиум' },
  { name: 'Водка Премиум Кристалл' },
  { name: 'Водка Праздничная' },
  { name: 'Водка Посольская' },
  { name: 'Водка Птичка Синичка' },
  { name: 'Водка Правдинская' },
  { name: 'Водка Pravda' },
  { name: 'Водка Potocki' },
  { name: 'Водка Polmos' },
  { name: 'Водка Portobello Road' },
  { name: 'Водка Purity' },
  { name: 'Водка Pau Maui' },
  { name: 'Водка Pienaar and Son' },
  { name: 'Водка Pod' },
  { name: 'Водка Попов' },
  { name: 'Водка Полярная' },
  { name: 'Водка Подмосковная' },
  { name: 'Водка Прима' },
  { name: 'Водка Привоз' },
  { name: 'Водка Прохоровское поле' },
  { name: 'Водка Русский стандарт' },
  { name: 'Водка Русский стандарт Оригинал' },
  { name: 'Водка Русский стандарт Платинум' },
  { name: 'Водка Русский стандарт Голд' },
  { name: 'Водка Русская' },
  { name: 'Водка Русская оригинальная' },
  { name: 'Водка Русская премиум' },
  { name: 'Водка Ржаная' },
  { name: 'Водка Ржаная классическая' },
  { name: 'Водка Родниковая' },
  { name: 'Водка Родник' },
  { name: 'Водка Родная' },
  { name: 'Водка Родная земля' },
  { name: 'Водка Романова' },
  { name: 'Водка Romanov' },
  { name: 'Водка Ruskova' },
  { name: 'Водка Reyka' },
  { name: 'Водка Ramsbury' },
  { name: 'Водка Retribution' },
  { name: 'Водка Respirited' },
  { name: 'Водка Roberto Cavalli' },
  { name: 'Водка Rutte' },
  { name: 'Водка Рублёвка' },
  { name: 'Водка Рубиновая' },
  { name: 'Водка Радомир' },
  { name: 'Водка Радость' },
  { name: 'Водка Разливная' },
  { name: 'Водка Региональная' },
  { name: 'Водка Рекорд' },
  { name: 'Водка Ретро' },
  { name: 'Водка Столичная' },
  { name: 'Водка Столичная Классическая' },
  { name: 'Водка Столичная Премиум' },
  { name: 'Водка Столичная Север' },
  { name: 'Водка Смирнофф' },
  { name: 'Водка Смирнофф Red Label' },
  { name: 'Водка Смирнофф No. 21' },
  { name: 'Водка Смирновъ' },
  { name: 'Водка Смирновъ №21' },
  { name: 'Водка Союз' },
  { name: 'Водка Серебряная' },
  { name: 'Водка Серебро Сибири' },
  { name: 'Водка Сибирская' },
  { name: 'Водка Сибирская кедровая' },
  { name: 'Водка Северное золото' },
  { name: 'Водка Славянская' },
  { name: 'Водка Славянская Премиум' },
  { name: 'Водка Старая марка' },
  { name: 'Водка Старая Казань' },
  { name: 'Водка Старая Москва' },
  { name: 'Водка Снежная' },
  { name: 'Водка Снежница' },
  { name: 'Водка Снежный барс' },
  { name: 'Водка Skyy' },
  { name: 'Водка Svedka' },
  { name: 'Водка Sacred' },
  { name: 'Водка Sipsmith' },
  { name: 'Водка Sauvelle' },
  { name: 'Водка Sheringham' },
  { name: 'Водка Silver Circle' },
  { name: 'Водка Spirit of Hven' },
  { name: 'Водка Savvy' },
  { name: 'Водка Snow' },
  { name: 'Водка Scorpion' },
  { name: 'Водка Silver Tree' },
  { name: 'Водка Сибирский характер' },
  { name: 'Водка Сосновый бор' },
  { name: 'Водка Солнечная' },
  { name: 'Водка Софія' },
  { name: 'Водка Софія Премиум' },
  { name: 'Водка Софія Золото' },
  { name: 'Водка Tito’s Handmade Vodka' },
  { name: 'Водка Тундра' },
  { name: 'Водка Тундра Аутентик' },
  { name: 'Водка Тундра Классическая' },
  { name: 'Водка Талка' },
  { name: 'Водка Talka' },
  { name: 'Водка Three Olives' },
  { name: 'Водка Three Olives Marilyn Monroe' },
  { name: 'Водка Thunder' },
  { name: 'Водка Tried and True' },
  { name: 'Водка Tanqueray' }, // хотя это джин, иногда в списках водок по ошибке, но пропустим если строго
  { name: 'Водка Tatra' }, // Tatra Tea иногда путают, но есть водочные вариации
  { name: 'Водка Tuica' }, // румынская/молдавская, иногда классифицируют как водку
  { name: 'Водка Tovarishch' },
  { name: 'Водка Tsar' },
  { name: 'Водка Tundra Premium' },
  { name: 'Водка Тяпница' },
  { name: 'Водка Турецкая ракти' }, // редкая/традиционная
  { name: 'Водка Тройка' },
  { name: 'Водка Тайга' },
  { name: 'Водка Ukiyo' },
  { name: 'Водка Utkins' },
  { name: 'Водка Fair' },
  { name: 'Водка Fallen Angel' },
  { name: 'Водка Finlandia' },
  { name: 'Водка Finlandia Lime' },
  { name: 'Водка Finlandia Grapefruit' },
  { name: 'Водка Finlandia Mango' },
  { name: 'Водка Firestarter' },
  { name: 'Водка Хортица' },
  { name: 'Водка Хортица Премиум' },
  { name: 'Водка Хортица Серебряная' },
  { name: 'Водка Хортица Абсолютная' },
  { name: 'Водка Хаски' },
  { name: 'Водка Хан' },
  { name: 'Водка Ханская' },
  { name: 'Водка Хреновая' }, // иногда как "Хреновуха", но встречается как чистая водка с хреном
  { name: 'Водка Хлебная' },
  { name: 'Водка Царская' },
  { name: 'Водка Царская Оригинальная' },
  { name: 'Водка Царская Золотая' },
  { name: 'Водка Царская Ледяная' },
  { name: 'Водка Царская Органик' },
  { name: 'Водка Царская' }, // вкусовые вариации: арбуз, персик, вишня, яблоко, клубника и т.д. — их 11+ в линейке
  { name: 'Водка Царская Чарка' },
  { name: 'Водка Царская Чарка Золотая' },
  { name: 'Водка Царская Чарка Серебряная' },
  { name: 'Водка Царская Чарка Классическая' },
  { name: 'Водка Царская Чарка на русских хлебах' },
  { name: 'Водка Царская Чарка на семечках' },
  { name: 'Водка Чарка' },
  { name: 'Водка Чарка Беспохмельная' },
  { name: 'Водка Чистые Росы' },
  { name: 'Водка Чистые Росы Классическая' },
  { name: 'Водка Чистые Росы из ржаного зерна' },
  { name: 'Водка Чистые Росы из ячменного зерна' },
  { name: 'Водка Чистые Росы с перцем' },
  { name: 'Водка Чистые Росы Органик' },
  { name: 'Водка Шустов' },
  { name: 'Водка Шустов Сильвер' },
  { name: 'Водка Шустов Красная' },
  { name: 'Водка Шустов Голд' },
  { name: 'Водка Шустов Особенная №1' },
  { name: 'Водка Шустов Премиум Голд' },
  { name: 'Водка Шустов Люкс' },
  { name: 'Водка Тайга Штоф' },
  { name: 'Водка Taiga Shtof' },
  { name: 'Водка Taiga Shtof Классическая' },
  { name: 'Водка Штоф' },
  { name: 'Водка Ять' },
  { name: 'Водка Ять Классическая' },
  { name: 'Водка Ять с хреном' },
]
